REM THIS IS FILE   ZIPMACR.BAT
REM PURPOSE--ZIP ALL    MACRO    FILES FOR DATAPLOT
REM DATE--SEPTEMBER 1993
REM DATE--JUNE      1995
REM DATE--JULY      1995
 
REM -----ZIP DATAPLOT'S MACRO FILES (==> MACRFILE.EXE)-----
 
DEL      MACRFILE.ZIP
DEL      MACRFILE.EXE
 
PKZIP    MACRFILE.ZIP *.*
ZIPTOEXE MACRFILE.ZIP
