C-----THIS IS COMMON/INCLUDE FILE DPCOMC.INC-----
C     THIS IS COMMON FOR MACHINE CONSTANTS
C
C               **************************
C               **************************
C               **  DEFINE THE INTEGER  **
C               **  MACHINE CONSTANTS   **
C               **  ARRAY               **
C               **************************
C               **************************
C
      COMMON /IMACH/I1MACH(16)
C
C               ********************************************************
C               ********************************************************
C               **  DEFINE THE REAL (SINGLE PRECISION FLOATING POINT)  *
C               **  MACHINE CONSTANTS                                  *
C               **  ARRAY                                              *
C               ********************************************************
C               ********************************************************
C
      COMMON /RMACH/R1MACH(5)
C
C               ***********************************
C               ***********************************
C               **  DEFINE THE DOUBLE PRECISION  **
C               **  MACHINE CONSTANTS            **
C               **  ARRAY                        **
C               ***********************************
C               ***********************************
C
      DOUBLE PRECISION D1MACH
C
      COMMON /DMACH/D1MACH(5)
C
