!-----THIS IS COMMON/INCLUDE FILE DPCOMC.INC-----
!     THIS IS COMMON FOR MACHINE CONSTANTS
!
!               **************************
!               **************************
!               **  DEFINE THE INTEGER  **
!               **  MACHINE CONSTANTS   **
!               **  ARRAY               **
!               **************************
!               **************************
!
      COMMON /IMACH/I1MACH(16)
!
!               ********************************************************
!               ********************************************************
!               **  DEFINE THE REAL (SINGLE PRECISION FLOATING POINT)  *
!               **  MACHINE CONSTANTS                                  *
!               **  ARRAY                                              *
!               ********************************************************
!               ********************************************************
!
      COMMON /RMACH/R1MACH(5)
!
!               ***********************************
!               ***********************************
!               **  DEFINE THE DOUBLE PRECISION  **
!               **  MACHINE CONSTANTS            **
!               **  ARRAY                        **
!               ***********************************
!               ***********************************
!
      DOUBLE PRECISION D1MACH
!
      COMMON /DMACH/D1MACH(5)
!
